// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.1
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef XADD_TEN_H
#define XADD_TEN_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xadd_ten_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Axi4lites_BaseAddress;
} XAdd_ten_Config;
#endif

typedef struct {
    u32 Axi4lites_BaseAddress;
    u32 IsReady;
} XAdd_ten;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XAdd_ten_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XAdd_ten_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XAdd_ten_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XAdd_ten_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XAdd_ten_Initialize(XAdd_ten *InstancePtr, u16 DeviceId);
XAdd_ten_Config* XAdd_ten_LookupConfig(u16 DeviceId);
int XAdd_ten_CfgInitialize(XAdd_ten *InstancePtr, XAdd_ten_Config *ConfigPtr);
#else
int XAdd_ten_Initialize(XAdd_ten *InstancePtr, const char* InstanceName);
int XAdd_ten_Release(XAdd_ten *InstancePtr);
#endif


void XAdd_ten_SetInput_r(XAdd_ten *InstancePtr, u32 Data);
u32 XAdd_ten_GetInput_r(XAdd_ten *InstancePtr);
u32 XAdd_ten_GetOutput_r(XAdd_ten *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
