// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.1
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xadd_five.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XAdd_five_CfgInitialize(XAdd_five *InstancePtr, XAdd_five_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Axi4lites_BaseAddress = ConfigPtr->Axi4lites_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XAdd_five_SetInput_r(XAdd_five *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XAdd_five_WriteReg(InstancePtr->Axi4lites_BaseAddress, XADD_FIVE_AXI4LITES_ADDR_INPUT_R_DATA, Data);
}

u32 XAdd_five_GetInput_r(XAdd_five *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XAdd_five_ReadReg(InstancePtr->Axi4lites_BaseAddress, XADD_FIVE_AXI4LITES_ADDR_INPUT_R_DATA);
    return Data;
}

u32 XAdd_five_GetOutput_r(XAdd_five *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XAdd_five_ReadReg(InstancePtr->Axi4lites_BaseAddress, XADD_FIVE_AXI4LITES_ADDR_OUTPUT_R_DATA);
    return Data;
}

