#pragma line 1 "add_ten.cpp" ::: -10
#pragma line 1 "add_ten.cpp" 1 ::: -9
#pragma line 1 "<built-in>" 1 ::: -8
#pragma line 1 "<built-in>" 3 ::: -7
#pragma line 152 "<built-in>" 3 ::: -6
#pragma line 1 "<command line>" 1 ::: -5
#pragma line 1 "C:/Xilinx/Vivado_HLS/2014.1/common/technology/autopilot\\etc/autopilot_ssdm_op.h" 1 ::: 3
#pragma line 99 "C:/Xilinx/Vivado_HLS/2014.1/common/technology/autopilot\\etc/autopilot_ssdm_op.h" ::: 10
#pragma line 375 "C:/Xilinx/Vivado_HLS/2014.1/common/technology/autopilot\\etc/autopilot_ssdm_op.h" ::: 149
#pragma line 9 "<command line>" 2 ::: 152
#pragma line 1 "<built-in>" 2 ::: 153
#pragma line 1 "add_ten.cpp" 2 ::: 154
#pragma line 11 "add_ten.cpp" ::: 167
