// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.1
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xadd_ten.h"

extern XAdd_ten_Config XAdd_ten_ConfigTable[];

XAdd_ten_Config *XAdd_ten_LookupConfig(u16 DeviceId) {
	XAdd_ten_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XADD_TEN_NUM_INSTANCES; Index++) {
		if (XAdd_ten_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XAdd_ten_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XAdd_ten_Initialize(XAdd_ten *InstancePtr, u16 DeviceId) {
	XAdd_ten_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XAdd_ten_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XAdd_ten_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

